server:
  port: 8999
##关闭熔断
#feign:
#  hystrix:
#    enabled: false
spring:
  session:
    store-type: redis
  #缓存
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  #数据库
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iForms?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Passw0rd12

    # 配置监控统计拦截的filters
    filters: stat
    # 最大连接数
    max-active: 10
    # 初始化配置
    initial-size: 5
    # 获取连接超时时间
    max-wait: 60000
    # 最小连接数
    min-idle: 5
    # 连接有效性检测时间
    time-between-eviction-runs-millis: 60000
    # 最大空闲时间
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20

    stat-view-servlet:
      url-pattern: /druid/*
      reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  application:
    name: iforms
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #邮件
  mail:
    host: mailgot.xxx.com
    username: Api.support.css@xxx.com  #用户名
    password: xxx                    #密码
  #下面是安全认证，不加会报503错误
  properties:
    mail:
    smtp:
      auth: true
      starttls:
        enable: true
        required: true
      default-encoding: UTF-8
fromMail: Api.support.css@xxx.com
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.microastudio.iforms.modules.*

#redis password
redis:
  reset_password_token:
    expire: 300
  password_error_log:
    expire: 10800
    max_number: 5

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#是否开启 swagger-ui
swagger:
  enabled: true
#是否开启 验证码
verificationCode:
  enabled: false
#sql 日志打印  root（项目）日志打印级别
logging:
  level:
    #    root: warn
    com:
      microastudio:
        iforms:
          mapper: debug
  config:
    classpath: logback-spring.xml

iforms:
  log-path: /Users/peng/data/logs/iforms
