##关闭熔断
#feign:
#  hystrix:
#    enabled: false
spring:
  session:
    store-type: redis
  #缓存
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  #数据库
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iForms?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Passw0rd12
    filters: stat
    max-active: 10
    initial-size: 5
    max-wait: 60000
    min-idle: 5
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
  application:
    name: iforms
  #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #邮件
  mail:
    host: mailgot.xxx.com
    username: Api.support.css@xxx.com  #用户名
    password: xxx                    #密码
  #下面是安全认证，不加会报503错误
  properties:
    mail:
    smtp:
      auth: true
      starttls:
        enable: true
        required: true
      default-encoding: UTF-8
fromMail: Api.support.css@xxx.com
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.microastudio.*.entity

#redis password
redis:
  reset_password_token:
    expire: 300
  password_error_log:
    expire: 10800
    max_number: 5
#是否开启 swagger-ui
swagger:
  enabled: true
#sql 日志打印  root（项目）日志打印级别
logging:
  level:
    #    root: warn
    com:
      microastudio:
        iforms:
          mapper: debug
  config:
    classpath: logback-spring.xml

iforms:
  log-path: /Users/peng/data/logs/iforms

